//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaCliente.WSDepartamentos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WSDepartamentos.WSDepartamentosSoap")]
    public interface WSDepartamentosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarDepartamentosResult del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarDepartamentos", ReplyAction="*")]
        PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse ConsultarDepartamentos(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarDepartamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse> ConsultarDepartamentosAsync(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento departamento del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarDepartamento", ReplyAction="*")]
        PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse InsertarDepartamento(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse> InsertarDepartamentoAsync(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento departamento del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarDepartamento", ReplyAction="*")]
        PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse EliminarDepartamento(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse> EliminarDepartamentoAsync(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDepartamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDepartamentos", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequestBody Body;
        
        public ConsultarDepartamentosRequest() {
        }
        
        public ConsultarDepartamentosRequest(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarDepartamentosRequestBody {
        
        public ConsultarDepartamentosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDepartamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDepartamentosResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponseBody Body;
        
        public ConsultarDepartamentosResponse() {
        }
        
        public ConsultarDepartamentosResponse(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConsultarDepartamentosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarDepartamentosResult;
        
        public ConsultarDepartamentosResponseBody() {
        }
        
        public ConsultarDepartamentosResponseBody(string ConsultarDepartamentosResult) {
            this.ConsultarDepartamentosResult = ConsultarDepartamentosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDepartamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDepartamento", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequestBody Body;
        
        public InsertarDepartamentoRequest() {
        }
        
        public InsertarDepartamentoRequest(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarDepartamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string departamento;
        
        public InsertarDepartamentoRequestBody() {
        }
        
        public InsertarDepartamentoRequestBody(string departamento) {
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDepartamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDepartamentoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponseBody Body;
        
        public InsertarDepartamentoResponse() {
        }
        
        public InsertarDepartamentoResponse(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarDepartamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarDepartamentoResult;
        
        public InsertarDepartamentoResponseBody() {
        }
        
        public InsertarDepartamentoResponseBody(bool InsertarDepartamentoResult) {
            this.InsertarDepartamentoResult = InsertarDepartamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarDepartamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarDepartamento", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequestBody Body;
        
        public EliminarDepartamentoRequest() {
        }
        
        public EliminarDepartamentoRequest(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EliminarDepartamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string departamento;
        
        public EliminarDepartamentoRequestBody() {
        }
        
        public EliminarDepartamentoRequestBody(string departamento) {
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarDepartamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarDepartamentoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponseBody Body;
        
        public EliminarDepartamentoResponse() {
        }
        
        public EliminarDepartamentoResponse(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EliminarDepartamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarDepartamentoResult;
        
        public EliminarDepartamentoResponseBody() {
        }
        
        public EliminarDepartamentoResponseBody(bool EliminarDepartamentoResult) {
            this.EliminarDepartamentoResult = EliminarDepartamentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDepartamentosSoapChannel : PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDepartamentosSoapClient : System.ServiceModel.ClientBase<PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap>, PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap {
        
        public WSDepartamentosSoapClient() {
        }
        
        public WSDepartamentosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDepartamentosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDepartamentosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDepartamentosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.ConsultarDepartamentos(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest request) {
            return base.Channel.ConsultarDepartamentos(request);
        }
        
        public string ConsultarDepartamentos() {
            PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest inValue = new PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequestBody();
            PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse retVal = ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).ConsultarDepartamentos(inValue);
            return retVal.Body.ConsultarDepartamentosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse> PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.ConsultarDepartamentosAsync(PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest request) {
            return base.Channel.ConsultarDepartamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosResponse> ConsultarDepartamentosAsync() {
            PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest inValue = new PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.ConsultarDepartamentosRequestBody();
            return ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).ConsultarDepartamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.InsertarDepartamento(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest request) {
            return base.Channel.InsertarDepartamento(request);
        }
        
        public bool InsertarDepartamento(string departamento) {
            PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest inValue = new PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse retVal = ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).InsertarDepartamento(inValue);
            return retVal.Body.InsertarDepartamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse> PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.InsertarDepartamentoAsync(PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest request) {
            return base.Channel.InsertarDepartamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoResponse> InsertarDepartamentoAsync(string departamento) {
            PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest inValue = new PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.InsertarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            return ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).InsertarDepartamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.EliminarDepartamento(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest request) {
            return base.Channel.EliminarDepartamento(request);
        }
        
        public bool EliminarDepartamento(string departamento) {
            PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest inValue = new PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse retVal = ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).EliminarDepartamento(inValue);
            return retVal.Body.EliminarDepartamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse> PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap.EliminarDepartamentoAsync(PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest request) {
            return base.Channel.EliminarDepartamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoResponse> EliminarDepartamentoAsync(string departamento) {
            PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest inValue = new PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequest();
            inValue.Body = new PuntoVentaCliente.WSDepartamentos.EliminarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            return ((PuntoVentaCliente.WSDepartamentos.WSDepartamentosSoap)(this)).EliminarDepartamentoAsync(inValue);
        }
    }
}
