//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaCliente.WSEmpleados {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WSEmpleados.WSEmpleadosSoap")]
    public interface WSEmpleadosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarEmpleados", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse ConsultarEmpleados(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarEmpleados", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse> ConsultarEmpleadosAsync(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jsonEmpleado del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarEmpleados", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse InsertarEmpleados(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarEmpleados", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse> InsertarEmpleadosAsync(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarEmpleado", ReplyAction="*")]
        bool EliminarEmpleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jsonEmpleados del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ActualizarEmpleado", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse ActualizarEmpleado(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ActualizarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse> ActualizarEmpleadoAsync(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento busqueda del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/BuscarEmpleado", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse BuscarEmpleado(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/BuscarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse> BuscarEmpleadoAsync(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Login", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.LoginResponse Login(PuntoVentaCliente.WSEmpleados.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.LoginResponse> LoginAsync(PuntoVentaCliente.WSEmpleados.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/UsuarioDatos", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse UsuarioDatos(PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/UsuarioDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse> UsuarioDatosAsync(PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/UsuarioActualizar", ReplyAction="*")]
        PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse UsuarioActualizar(PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/UsuarioActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse> UsuarioActualizarAsync(PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleados", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequestBody Body;
        
        public ConsultarEmpleadosRequest() {
        }
        
        public ConsultarEmpleadosRequest(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConsultarEmpleadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public ConsultarEmpleadosRequestBody() {
        }
        
        public ConsultarEmpleadosRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleadosResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponseBody Body;
        
        public ConsultarEmpleadosResponse() {
        }
        
        public ConsultarEmpleadosResponse(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConsultarEmpleadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarEmpleadosResult;
        
        public ConsultarEmpleadosResponseBody() {
        }
        
        public ConsultarEmpleadosResponseBody(string ConsultarEmpleadosResult) {
            this.ConsultarEmpleadosResult = ConsultarEmpleadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarEmpleados", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequestBody Body;
        
        public InsertarEmpleadosRequest() {
        }
        
        public InsertarEmpleadosRequest(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarEmpleadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonEmpleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jsonUsuario;
        
        public InsertarEmpleadosRequestBody() {
        }
        
        public InsertarEmpleadosRequestBody(string jsonEmpleado, string jsonUsuario) {
            this.jsonEmpleado = jsonEmpleado;
            this.jsonUsuario = jsonUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarEmpleadosResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponseBody Body;
        
        public InsertarEmpleadosResponse() {
        }
        
        public InsertarEmpleadosResponse(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarEmpleadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarEmpleadosResult;
        
        public InsertarEmpleadosResponseBody() {
        }
        
        public InsertarEmpleadosResponseBody(bool InsertarEmpleadosResult) {
            this.InsertarEmpleadosResult = InsertarEmpleadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarEmpleado", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequestBody Body;
        
        public ActualizarEmpleadoRequest() {
        }
        
        public ActualizarEmpleadoRequest(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ActualizarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonEmpleados;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jsonUsuarios;
        
        public ActualizarEmpleadoRequestBody() {
        }
        
        public ActualizarEmpleadoRequestBody(string jsonEmpleados, string jsonUsuarios) {
            this.jsonEmpleados = jsonEmpleados;
            this.jsonUsuarios = jsonUsuarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarEmpleadoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponseBody Body;
        
        public ActualizarEmpleadoResponse() {
        }
        
        public ActualizarEmpleadoResponse(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ActualizarEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarEmpleadoResult;
        
        public ActualizarEmpleadoResponseBody() {
        }
        
        public ActualizarEmpleadoResponseBody(bool ActualizarEmpleadoResult) {
            this.ActualizarEmpleadoResult = ActualizarEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarEmpleado", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequestBody Body;
        
        public BuscarEmpleadoRequest() {
        }
        
        public BuscarEmpleadoRequest(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BuscarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        public BuscarEmpleadoRequestBody() {
        }
        
        public BuscarEmpleadoRequestBody(string busqueda, string usuario) {
            this.busqueda = busqueda;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarEmpleadoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponseBody Body;
        
        public BuscarEmpleadoResponse() {
        }
        
        public BuscarEmpleadoResponse(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BuscarEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarEmpleadoResult;
        
        public BuscarEmpleadoResponseBody() {
        }
        
        public BuscarEmpleadoResponseBody(string BuscarEmpleadoResult) {
            this.BuscarEmpleadoResult = BuscarEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(PuntoVentaCliente.WSEmpleados.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(PuntoVentaCliente.WSEmpleados.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioDatos", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.UsuarioDatosRequestBody Body;
        
        public UsuarioDatosRequest() {
        }
        
        public UsuarioDatosRequest(PuntoVentaCliente.WSEmpleados.UsuarioDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UsuarioDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public UsuarioDatosRequestBody() {
        }
        
        public UsuarioDatosRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioDatosResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.UsuarioDatosResponseBody Body;
        
        public UsuarioDatosResponse() {
        }
        
        public UsuarioDatosResponse(PuntoVentaCliente.WSEmpleados.UsuarioDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UsuarioDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsuarioDatosResult;
        
        public UsuarioDatosResponseBody() {
        }
        
        public UsuarioDatosResponseBody(string UsuarioDatosResult) {
            this.UsuarioDatosResult = UsuarioDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioActualizar", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequestBody Body;
        
        public UsuarioActualizarRequest() {
        }
        
        public UsuarioActualizarRequest(PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UsuarioActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public UsuarioActualizarRequestBody() {
        }
        
        public UsuarioActualizarRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioActualizarResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponseBody Body;
        
        public UsuarioActualizarResponse() {
        }
        
        public UsuarioActualizarResponse(PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UsuarioActualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UsuarioActualizarResult;
        
        public UsuarioActualizarResponseBody() {
        }
        
        public UsuarioActualizarResponseBody(bool UsuarioActualizarResult) {
            this.UsuarioActualizarResult = UsuarioActualizarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEmpleadosSoapChannel : PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEmpleadosSoapClient : System.ServiceModel.ClientBase<PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap>, PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap {
        
        public WSEmpleadosSoapClient() {
        }
        
        public WSEmpleadosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEmpleadosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEmpleadosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEmpleadosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.ConsultarEmpleados(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest request) {
            return base.Channel.ConsultarEmpleados(request);
        }
        
        public string ConsultarEmpleados(string usuario) {
            PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest inValue = new PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequestBody();
            inValue.Body.usuario = usuario;
            PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).ConsultarEmpleados(inValue);
            return retVal.Body.ConsultarEmpleadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.ConsultarEmpleadosAsync(PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest request) {
            return base.Channel.ConsultarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosResponse> ConsultarEmpleadosAsync(string usuario) {
            PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest inValue = new PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.ConsultarEmpleadosRequestBody();
            inValue.Body.usuario = usuario;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).ConsultarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.InsertarEmpleados(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest request) {
            return base.Channel.InsertarEmpleados(request);
        }
        
        public bool InsertarEmpleados(string jsonEmpleado, string jsonUsuario) {
            PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest inValue = new PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequestBody();
            inValue.Body.jsonEmpleado = jsonEmpleado;
            inValue.Body.jsonUsuario = jsonUsuario;
            PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).InsertarEmpleados(inValue);
            return retVal.Body.InsertarEmpleadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.InsertarEmpleadosAsync(PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest request) {
            return base.Channel.InsertarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.InsertarEmpleadosResponse> InsertarEmpleadosAsync(string jsonEmpleado, string jsonUsuario) {
            PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest inValue = new PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.InsertarEmpleadosRequestBody();
            inValue.Body.jsonEmpleado = jsonEmpleado;
            inValue.Body.jsonUsuario = jsonUsuario;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).InsertarEmpleadosAsync(inValue);
        }
        
        public bool EliminarEmpleado(int id) {
            return base.Channel.EliminarEmpleado(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(int id) {
            return base.Channel.EliminarEmpleadoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.ActualizarEmpleado(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest request) {
            return base.Channel.ActualizarEmpleado(request);
        }
        
        public bool ActualizarEmpleado(string jsonEmpleados, string jsonUsuarios) {
            PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest inValue = new PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequestBody();
            inValue.Body.jsonEmpleados = jsonEmpleados;
            inValue.Body.jsonUsuarios = jsonUsuarios;
            PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).ActualizarEmpleado(inValue);
            return retVal.Body.ActualizarEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.ActualizarEmpleadoAsync(PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest request) {
            return base.Channel.ActualizarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoResponse> ActualizarEmpleadoAsync(string jsonEmpleados, string jsonUsuarios) {
            PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest inValue = new PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.ActualizarEmpleadoRequestBody();
            inValue.Body.jsonEmpleados = jsonEmpleados;
            inValue.Body.jsonUsuarios = jsonUsuarios;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).ActualizarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.BuscarEmpleado(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest request) {
            return base.Channel.BuscarEmpleado(request);
        }
        
        public string BuscarEmpleado(string busqueda, string usuario) {
            PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest inValue = new PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequestBody();
            inValue.Body.busqueda = busqueda;
            inValue.Body.usuario = usuario;
            PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).BuscarEmpleado(inValue);
            return retVal.Body.BuscarEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.BuscarEmpleadoAsync(PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest request) {
            return base.Channel.BuscarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.BuscarEmpleadoResponse> BuscarEmpleadoAsync(string busqueda, string usuario) {
            PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest inValue = new PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.BuscarEmpleadoRequestBody();
            inValue.Body.busqueda = busqueda;
            inValue.Body.usuario = usuario;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).BuscarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.LoginResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.Login(PuntoVentaCliente.WSEmpleados.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string usuario, string password) {
            PuntoVentaCliente.WSEmpleados.LoginRequest inValue = new PuntoVentaCliente.WSEmpleados.LoginRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            PuntoVentaCliente.WSEmpleados.LoginResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.LoginResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.LoginAsync(PuntoVentaCliente.WSEmpleados.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.LoginResponse> LoginAsync(string usuario, string password) {
            PuntoVentaCliente.WSEmpleados.LoginRequest inValue = new PuntoVentaCliente.WSEmpleados.LoginRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.UsuarioDatos(PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest request) {
            return base.Channel.UsuarioDatos(request);
        }
        
        public string UsuarioDatos(string usuario) {
            PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest inValue = new PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.UsuarioDatosRequestBody();
            inValue.Body.usuario = usuario;
            PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).UsuarioDatos(inValue);
            return retVal.Body.UsuarioDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.UsuarioDatosAsync(PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest request) {
            return base.Channel.UsuarioDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioDatosResponse> UsuarioDatosAsync(string usuario) {
            PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest inValue = new PuntoVentaCliente.WSEmpleados.UsuarioDatosRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.UsuarioDatosRequestBody();
            inValue.Body.usuario = usuario;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).UsuarioDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.UsuarioActualizar(PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest request) {
            return base.Channel.UsuarioActualizar(request);
        }
        
        public bool UsuarioActualizar(string json) {
            PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest inValue = new PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequestBody();
            inValue.Body.json = json;
            PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse retVal = ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).UsuarioActualizar(inValue);
            return retVal.Body.UsuarioActualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse> PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap.UsuarioActualizarAsync(PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest request) {
            return base.Channel.UsuarioActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSEmpleados.UsuarioActualizarResponse> UsuarioActualizarAsync(string json) {
            PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest inValue = new PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequest();
            inValue.Body = new PuntoVentaCliente.WSEmpleados.UsuarioActualizarRequestBody();
            inValue.Body.json = json;
            return ((PuntoVentaCliente.WSEmpleados.WSEmpleadosSoap)(this)).UsuarioActualizarAsync(inValue);
        }
    }
}
