//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaCliente.WSPuestos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WSPuestos.WSPuestosSoap")]
    public interface WSPuestosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarPuestosResult del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarPuestos", ReplyAction="*")]
        PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse ConsultarPuestos(PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarPuestos", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse> ConsultarPuestosAsync(PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento puesto del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarPuesto", ReplyAction="*")]
        PuntoVentaCliente.WSPuestos.InsertarPuestoResponse InsertarPuesto(PuntoVentaCliente.WSPuestos.InsertarPuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarPuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.InsertarPuestoResponse> InsertarPuestoAsync(PuntoVentaCliente.WSPuestos.InsertarPuestoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento puesto del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarPuesto", ReplyAction="*")]
        PuntoVentaCliente.WSPuestos.EliminarPuestoResponse EliminarPuesto(PuntoVentaCliente.WSPuestos.EliminarPuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarPuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.EliminarPuestoResponse> EliminarPuestoAsync(PuntoVentaCliente.WSPuestos.EliminarPuestoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPuestosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPuestos", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.ConsultarPuestosRequestBody Body;
        
        public ConsultarPuestosRequest() {
        }
        
        public ConsultarPuestosRequest(PuntoVentaCliente.WSPuestos.ConsultarPuestosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarPuestosRequestBody {
        
        public ConsultarPuestosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPuestosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPuestosResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.ConsultarPuestosResponseBody Body;
        
        public ConsultarPuestosResponse() {
        }
        
        public ConsultarPuestosResponse(PuntoVentaCliente.WSPuestos.ConsultarPuestosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConsultarPuestosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarPuestosResult;
        
        public ConsultarPuestosResponseBody() {
        }
        
        public ConsultarPuestosResponseBody(string ConsultarPuestosResult) {
            this.ConsultarPuestosResult = ConsultarPuestosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPuesto", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.InsertarPuestoRequestBody Body;
        
        public InsertarPuestoRequest() {
        }
        
        public InsertarPuestoRequest(PuntoVentaCliente.WSPuestos.InsertarPuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarPuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string puesto;
        
        public InsertarPuestoRequestBody() {
        }
        
        public InsertarPuestoRequestBody(string puesto) {
            this.puesto = puesto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPuestoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.InsertarPuestoResponseBody Body;
        
        public InsertarPuestoResponse() {
        }
        
        public InsertarPuestoResponse(PuntoVentaCliente.WSPuestos.InsertarPuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarPuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarPuestoResult;
        
        public InsertarPuestoResponseBody() {
        }
        
        public InsertarPuestoResponseBody(bool InsertarPuestoResult) {
            this.InsertarPuestoResult = InsertarPuestoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPuesto", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.EliminarPuestoRequestBody Body;
        
        public EliminarPuestoRequest() {
        }
        
        public EliminarPuestoRequest(PuntoVentaCliente.WSPuestos.EliminarPuestoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EliminarPuestoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string puesto;
        
        public EliminarPuestoRequestBody() {
        }
        
        public EliminarPuestoRequestBody(string puesto) {
            this.puesto = puesto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPuestoResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSPuestos.EliminarPuestoResponseBody Body;
        
        public EliminarPuestoResponse() {
        }
        
        public EliminarPuestoResponse(PuntoVentaCliente.WSPuestos.EliminarPuestoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class EliminarPuestoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarPuestoResult;
        
        public EliminarPuestoResponseBody() {
        }
        
        public EliminarPuestoResponseBody(bool EliminarPuestoResult) {
            this.EliminarPuestoResult = EliminarPuestoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPuestosSoapChannel : PuntoVentaCliente.WSPuestos.WSPuestosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPuestosSoapClient : System.ServiceModel.ClientBase<PuntoVentaCliente.WSPuestos.WSPuestosSoap>, PuntoVentaCliente.WSPuestos.WSPuestosSoap {
        
        public WSPuestosSoapClient() {
        }
        
        public WSPuestosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPuestosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPuestosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPuestosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse PuntoVentaCliente.WSPuestos.WSPuestosSoap.ConsultarPuestos(PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest request) {
            return base.Channel.ConsultarPuestos(request);
        }
        
        public string ConsultarPuestos() {
            PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest inValue = new PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.ConsultarPuestosRequestBody();
            PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse retVal = ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).ConsultarPuestos(inValue);
            return retVal.Body.ConsultarPuestosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse> PuntoVentaCliente.WSPuestos.WSPuestosSoap.ConsultarPuestosAsync(PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest request) {
            return base.Channel.ConsultarPuestosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.ConsultarPuestosResponse> ConsultarPuestosAsync() {
            PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest inValue = new PuntoVentaCliente.WSPuestos.ConsultarPuestosRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.ConsultarPuestosRequestBody();
            return ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).ConsultarPuestosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSPuestos.InsertarPuestoResponse PuntoVentaCliente.WSPuestos.WSPuestosSoap.InsertarPuesto(PuntoVentaCliente.WSPuestos.InsertarPuestoRequest request) {
            return base.Channel.InsertarPuesto(request);
        }
        
        public bool InsertarPuesto(string puesto) {
            PuntoVentaCliente.WSPuestos.InsertarPuestoRequest inValue = new PuntoVentaCliente.WSPuestos.InsertarPuestoRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.InsertarPuestoRequestBody();
            inValue.Body.puesto = puesto;
            PuntoVentaCliente.WSPuestos.InsertarPuestoResponse retVal = ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).InsertarPuesto(inValue);
            return retVal.Body.InsertarPuestoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.InsertarPuestoResponse> PuntoVentaCliente.WSPuestos.WSPuestosSoap.InsertarPuestoAsync(PuntoVentaCliente.WSPuestos.InsertarPuestoRequest request) {
            return base.Channel.InsertarPuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.InsertarPuestoResponse> InsertarPuestoAsync(string puesto) {
            PuntoVentaCliente.WSPuestos.InsertarPuestoRequest inValue = new PuntoVentaCliente.WSPuestos.InsertarPuestoRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.InsertarPuestoRequestBody();
            inValue.Body.puesto = puesto;
            return ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).InsertarPuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSPuestos.EliminarPuestoResponse PuntoVentaCliente.WSPuestos.WSPuestosSoap.EliminarPuesto(PuntoVentaCliente.WSPuestos.EliminarPuestoRequest request) {
            return base.Channel.EliminarPuesto(request);
        }
        
        public bool EliminarPuesto(string puesto) {
            PuntoVentaCliente.WSPuestos.EliminarPuestoRequest inValue = new PuntoVentaCliente.WSPuestos.EliminarPuestoRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.EliminarPuestoRequestBody();
            inValue.Body.puesto = puesto;
            PuntoVentaCliente.WSPuestos.EliminarPuestoResponse retVal = ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).EliminarPuesto(inValue);
            return retVal.Body.EliminarPuestoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.EliminarPuestoResponse> PuntoVentaCliente.WSPuestos.WSPuestosSoap.EliminarPuestoAsync(PuntoVentaCliente.WSPuestos.EliminarPuestoRequest request) {
            return base.Channel.EliminarPuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSPuestos.EliminarPuestoResponse> EliminarPuestoAsync(string puesto) {
            PuntoVentaCliente.WSPuestos.EliminarPuestoRequest inValue = new PuntoVentaCliente.WSPuestos.EliminarPuestoRequest();
            inValue.Body = new PuntoVentaCliente.WSPuestos.EliminarPuestoRequestBody();
            inValue.Body.puesto = puesto;
            return ((PuntoVentaCliente.WSPuestos.WSPuestosSoap)(this)).EliminarPuestoAsync(inValue);
        }
    }
}
