//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaCliente.WSProveedores {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WSProveedores.WSProveedoresSoap")]
    public interface WSProveedoresSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarProveedoresResult del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarProveedores", ReplyAction="*")]
        PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse ConsultarProveedores(PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ConsultarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse> ConsultarProveedoresAsync(PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarProveedores", ReplyAction="*")]
        PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse InsertarProveedores(PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/InsertarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse> InsertarProveedoresAsync(PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarProveedores", ReplyAction="*")]
        bool EliminarProveedores(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/EliminarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProveedoresAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ActualizarProveedores", ReplyAction="*")]
        PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse ActualizarProveedores(PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/ActualizarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse> ActualizarProveedoresAsync(PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento busqueda del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/BuscarProveedores", ReplyAction="*")]
        PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse BuscarProveedores(PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/BuscarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse> BuscarProveedoresAsync(PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProveedores", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequestBody Body;
        
        public ConsultarProveedoresRequest() {
        }
        
        public ConsultarProveedoresRequest(PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarProveedoresRequestBody {
        
        public ConsultarProveedoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProveedoresResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponseBody Body;
        
        public ConsultarProveedoresResponse() {
        }
        
        public ConsultarProveedoresResponse(PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ConsultarProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarProveedoresResult;
        
        public ConsultarProveedoresResponseBody() {
        }
        
        public ConsultarProveedoresResponseBody(string ConsultarProveedoresResult) {
            this.ConsultarProveedoresResult = ConsultarProveedoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProveedores", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.InsertarProveedoresRequestBody Body;
        
        public InsertarProveedoresRequest() {
        }
        
        public InsertarProveedoresRequest(PuntoVentaCliente.WSProveedores.InsertarProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarProveedoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public InsertarProveedoresRequestBody() {
        }
        
        public InsertarProveedoresRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProveedoresResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.InsertarProveedoresResponseBody Body;
        
        public InsertarProveedoresResponse() {
        }
        
        public InsertarProveedoresResponse(PuntoVentaCliente.WSProveedores.InsertarProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class InsertarProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarProveedoresResult;
        
        public InsertarProveedoresResponseBody() {
        }
        
        public InsertarProveedoresResponseBody(bool InsertarProveedoresResult) {
            this.InsertarProveedoresResult = InsertarProveedoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProveedores", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequestBody Body;
        
        public ActualizarProveedoresRequest() {
        }
        
        public ActualizarProveedoresRequest(PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ActualizarProveedoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public ActualizarProveedoresRequestBody() {
        }
        
        public ActualizarProveedoresRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProveedoresResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponseBody Body;
        
        public ActualizarProveedoresResponse() {
        }
        
        public ActualizarProveedoresResponse(PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ActualizarProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProveedoresResult;
        
        public ActualizarProveedoresResponseBody() {
        }
        
        public ActualizarProveedoresResponseBody(bool ActualizarProveedoresResult) {
            this.ActualizarProveedoresResult = ActualizarProveedoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProveedores", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.BuscarProveedoresRequestBody Body;
        
        public BuscarProveedoresRequest() {
        }
        
        public BuscarProveedoresRequest(PuntoVentaCliente.WSProveedores.BuscarProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BuscarProveedoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busqueda;
        
        public BuscarProveedoresRequestBody() {
        }
        
        public BuscarProveedoresRequestBody(string busqueda) {
            this.busqueda = busqueda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProveedoresResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public PuntoVentaCliente.WSProveedores.BuscarProveedoresResponseBody Body;
        
        public BuscarProveedoresResponse() {
        }
        
        public BuscarProveedoresResponse(PuntoVentaCliente.WSProveedores.BuscarProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class BuscarProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarProveedoresResult;
        
        public BuscarProveedoresResponseBody() {
        }
        
        public BuscarProveedoresResponseBody(string BuscarProveedoresResult) {
            this.BuscarProveedoresResult = BuscarProveedoresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProveedoresSoapChannel : PuntoVentaCliente.WSProveedores.WSProveedoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProveedoresSoapClient : System.ServiceModel.ClientBase<PuntoVentaCliente.WSProveedores.WSProveedoresSoap>, PuntoVentaCliente.WSProveedores.WSProveedoresSoap {
        
        public WSProveedoresSoapClient() {
        }
        
        public WSProveedoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProveedoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse PuntoVentaCliente.WSProveedores.WSProveedoresSoap.ConsultarProveedores(PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest request) {
            return base.Channel.ConsultarProveedores(request);
        }
        
        public string ConsultarProveedores() {
            PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequestBody();
            PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse retVal = ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).ConsultarProveedores(inValue);
            return retVal.Body.ConsultarProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse> PuntoVentaCliente.WSProveedores.WSProveedoresSoap.ConsultarProveedoresAsync(PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest request) {
            return base.Channel.ConsultarProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ConsultarProveedoresResponse> ConsultarProveedoresAsync() {
            PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.ConsultarProveedoresRequestBody();
            return ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).ConsultarProveedoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse PuntoVentaCliente.WSProveedores.WSProveedoresSoap.InsertarProveedores(PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest request) {
            return base.Channel.InsertarProveedores(request);
        }
        
        public bool InsertarProveedores(string json) {
            PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.InsertarProveedoresRequestBody();
            inValue.Body.json = json;
            PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse retVal = ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).InsertarProveedores(inValue);
            return retVal.Body.InsertarProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse> PuntoVentaCliente.WSProveedores.WSProveedoresSoap.InsertarProveedoresAsync(PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest request) {
            return base.Channel.InsertarProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.InsertarProveedoresResponse> InsertarProveedoresAsync(string json) {
            PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.InsertarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.InsertarProveedoresRequestBody();
            inValue.Body.json = json;
            return ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).InsertarProveedoresAsync(inValue);
        }
        
        public bool EliminarProveedores(int id) {
            return base.Channel.EliminarProveedores(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProveedoresAsync(int id) {
            return base.Channel.EliminarProveedoresAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse PuntoVentaCliente.WSProveedores.WSProveedoresSoap.ActualizarProveedores(PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest request) {
            return base.Channel.ActualizarProveedores(request);
        }
        
        public bool ActualizarProveedores(string json) {
            PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequestBody();
            inValue.Body.json = json;
            PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse retVal = ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).ActualizarProveedores(inValue);
            return retVal.Body.ActualizarProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse> PuntoVentaCliente.WSProveedores.WSProveedoresSoap.ActualizarProveedoresAsync(PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest request) {
            return base.Channel.ActualizarProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.ActualizarProveedoresResponse> ActualizarProveedoresAsync(string json) {
            PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.ActualizarProveedoresRequestBody();
            inValue.Body.json = json;
            return ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).ActualizarProveedoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse PuntoVentaCliente.WSProveedores.WSProveedoresSoap.BuscarProveedores(PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest request) {
            return base.Channel.BuscarProveedores(request);
        }
        
        public string BuscarProveedores(string busqueda) {
            PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.BuscarProveedoresRequestBody();
            inValue.Body.busqueda = busqueda;
            PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse retVal = ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).BuscarProveedores(inValue);
            return retVal.Body.BuscarProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse> PuntoVentaCliente.WSProveedores.WSProveedoresSoap.BuscarProveedoresAsync(PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest request) {
            return base.Channel.BuscarProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVentaCliente.WSProveedores.BuscarProveedoresResponse> BuscarProveedoresAsync(string busqueda) {
            PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest inValue = new PuntoVentaCliente.WSProveedores.BuscarProveedoresRequest();
            inValue.Body = new PuntoVentaCliente.WSProveedores.BuscarProveedoresRequestBody();
            inValue.Body.busqueda = busqueda;
            return ((PuntoVentaCliente.WSProveedores.WSProveedoresSoap)(this)).BuscarProveedoresAsync(inValue);
        }
    }
}
